# @package _global_.model
# Model for energy generator: [data, source_latent, target_latent, noise]
_target_: layers.MLP
in_dims:
  - ${dataset.data_shape[0]}
  - ${experiment.latent_dim}
  - ${experiment.latent_dim}
  - ${generator.noise_dim}
hidden_dim: ${experiment.hidden_dim}
out_dim: ${dataset.data_shape[0]}
layers: 4

