# @package _global_.model
_target_: model.unet.ContextUnet
in_channels: ${dataset.data_shape[0]}  # 3 for RGB MNIST
n_feat: ${experiment.latent_dim}
latent_dim: ${experiment.latent_dim}
image_size: ${dataset.data_shape[1]}  # 28 for MNIST

