#!/usr/bin/env python3
"""
Parse ablation evaluation log files and extract final metrics into a CSV file.

This script reads log files from the logs/ directory that are generated by
run_evaluate_trellis_ablation.sh and extracts the final model metrics for each 
combination of:
- split: replicas-1, replicas-2, pdo21, pdo27, pdo75
- metric: mmd_energy, mmd_rbf, swd
- consecutive_ratio: 0.5, 0.2
- predictor_loss_weight: 0.1, 0.001

Usage:
    python parse_ablation_logs.py
    python parse_ablation_logs.py --logs_dir /path/to/logs
    python parse_ablation_logs.py --output results.csv
"""

import os
import re
import csv
import glob
import argparse
from pathlib import Path
from typing import Dict, List, Optional


def parse_log_file(filepath: str) -> Optional[Dict]:
    """
    Parse a single ablation log file and extract the relevant information.
    
    Returns a dict with:
        - split: the data split name
        - metric: the metric name (lowercase)
        - consecutive_ratio: the consecutive ratio parameter
        - predictor_loss_weight: the predictor loss weight parameter
        - model_mean: the mean model score
        - model_std: the std of model score
        - baseline_mean: the mean baseline score (if available)
        - baseline_std: the std of baseline score (if available)
    
    Returns None if the file cannot be parsed or is incomplete.
    """
    try:
        with open(filepath, 'r') as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None
    
    result = {}
    
    # Extract split, metric, consecutive_ratio, and predictor_loss_weight from the first line
    # Format: "Job X: Evaluating split=..., metric=..., consecutive_ratio=..., predictor_loss_weight=..."
    job_match = re.search(
        r'Job \d+: Evaluating split=([^,]+), metric=(\w+), consecutive_ratio=([\d.]+), predictor_loss_weight=([\d.e-]+)',
        content
    )
    if not job_match:
        print(f"Could not find job info in {filepath}")
        return None
    
    result['split'] = job_match.group(1)
    result['metric'] = job_match.group(2).lower()
    result['consecutive_ratio'] = float(job_match.group(3))
    result['predictor_loss_weight'] = float(job_match.group(4))
    
    # Find the FINAL RESULTS section and extract the metric line
    # Look for lines like:
    # MMD_ENERGY Model:    0.0923 +/- 0.0941  Baseline:    0.2256 +/- 0.2788
    # SWD    Model:    0.2379 +/- 0.0863
    # MMD_RBF Model:    0.0097 +/- 0.0107  Baseline:    0.0168 +/- 0.0211
    
    # Find the final results section
    final_section = re.search(r'FINAL RESULTS.*?={20,}(.*)', content, re.DOTALL)
    if not final_section:
        print(f"Could not find FINAL RESULTS section in {filepath}")
        return None
    
    final_content = final_section.group(1)
    
    # Pattern for metric line with optional baseline
    # Handles: MMD_ENERGY, MMD_RBF, SWD
    metric_pattern = r'(MMD_ENERGY|MMD_RBF|SWD)\s+Model:\s+([\d.]+)\s*\+/-\s*([\d.]+)(?:\s+Baseline:\s+([\d.]+)\s*\+/-\s*([\d.]+))?'
    
    metric_match = re.search(metric_pattern, final_content)
    if not metric_match:
        print(f"Could not find metric line in FINAL RESULTS of {filepath}")
        return None
    
    result['metric_name'] = metric_match.group(1).lower()
    result['model_mean'] = float(metric_match.group(2))
    result['model_std'] = float(metric_match.group(3))
    
    if metric_match.group(4) and metric_match.group(5):
        result['baseline_mean'] = float(metric_match.group(4))
        result['baseline_std'] = float(metric_match.group(5))
    else:
        result['baseline_mean'] = None
        result['baseline_std'] = None
    
    return result


def main():
    parser = argparse.ArgumentParser(description='Parse ablation evaluation log files and extract metrics to CSV.')
    parser.add_argument('--logs_dir', type=str, default=None,
                        help='Directory containing log files (default: ./logs)')
    parser.add_argument('--output', type=str, default=None,
                        help='Output CSV file path (default: ./ablation_results.csv)')
    parser.add_argument('--pattern', type=str, default='o_eval_ablation_*',
                        help='Glob pattern for log files (default: o_eval_ablation_*)')
    args = parser.parse_args()
    
    # Set default paths
    script_dir = Path(__file__).parent
    logs_dir = Path(args.logs_dir) if args.logs_dir else script_dir / 'logs'
    output_csv = Path(args.output) if args.output else script_dir / 'ablation_results.csv'
    
    # Find all matching log files
    log_pattern = str(logs_dir / args.pattern)
    log_files = glob.glob(log_pattern)
    
    print(f"Found {len(log_files)} log files matching pattern: {log_pattern}")
    
    if len(log_files) == 0:
        print("No log files found. Exiting.")
        return
    
    # Store all parsed results
    results = []
    
    for filepath in sorted(log_files):
        parsed = parse_log_file(filepath)
        if parsed is None:
            print(f"Skipping {filepath}: could not parse")
            continue
        
        results.append({
            'split': parsed['split'],
            'metric': parsed['metric'],
            'consecutive_ratio': parsed['consecutive_ratio'],
            'predictor_loss_weight': parsed['predictor_loss_weight'],
            'model_mean': parsed['model_mean'],
            'model_std': parsed['model_std'],
            'baseline_mean': parsed['baseline_mean'],
            'baseline_std': parsed['baseline_std'],
            'log_file': os.path.basename(filepath),
        })
    
    print(f"\nSuccessfully parsed {len(results)} log files")
    
    # Sort results for consistent output
    results.sort(key=lambda x: (x['split'], x['metric'], x['consecutive_ratio'], x['predictor_loss_weight']))
    
    # Write to CSV
    fieldnames = ['split', 'metric', 'consecutive_ratio', 'predictor_loss_weight',
                  'model_mean', 'model_std', 'baseline_mean', 'baseline_std', 'log_file']
    
    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        writer.writeheader()
        writer.writerows(results)
    
    print(f"\nResults saved to: {output_csv}")
    
    # Print a summary table
    print("\n" + "="*120)
    print("ABLATION RESULTS SUMMARY")
    print("="*120)
    
    # Group by split, metric, consecutive_ratio, predictor_loss_weight
    splits = ['replicas-1', 'replicas-2', 'pdo21', 'pdo27', 'pdo75']
    metrics = ['mmd_energy', 'mmd_rbf', 'swd']
    consecutive_ratios = [0.5, 0.2]
    predictor_loss_weights = [0.1, 0.001]
    
    # Create lookup dict
    lookup = {}
    for r in results:
        key = (r['split'], r['metric'], r['consecutive_ratio'], r['predictor_loss_weight'])
        lookup[key] = r
    
    # Print table header
    print(f"\n{'Split':<12} {'Metric':<12} {'Cons.Ratio':<12} {'Pred.Weight':<12} {'Model Mean':<12} {'Model Std':<12} {'Baseline Mean':<14} {'Baseline Std':<14}")
    print("-"*110)
    
    for split in splits:
        has_any = any((split, metric, cr, plw) in lookup 
                      for metric in metrics 
                      for cr in consecutive_ratios 
                      for plw in predictor_loss_weights)
        if not has_any:
            print(f"{split:<12} (no data found)")
            continue
            
        for metric in metrics:
            for cr in consecutive_ratios:
                for plw in predictor_loss_weights:
                    key = (split, metric, cr, plw)
                    if key in lookup:
                        r = lookup[key]
                        baseline_mean = f"{r['baseline_mean']:.6f}" if r['baseline_mean'] is not None else 'N/A'
                        baseline_std = f"{r['baseline_std']:.6f}" if r['baseline_std'] is not None else 'N/A'
                        print(f"{split:<12} {metric:<12} {cr:<12} {plw:<12} {r['model_mean']:<12.6f} {r['model_std']:<12.6f} {baseline_mean:<14} {baseline_std:<14}")
                    else:
                        print(f"{split:<12} {metric:<12} {cr:<12} {plw:<12} {'MISSING':<12} {'MISSING':<12} {'MISSING':<14} {'MISSING':<14}")
        print()  # Blank line between splits
    
    # Print summary statistics
    print("\n" + "="*120)
    print("AGGREGATED BY PARAMETER")
    print("="*120)
    
    # Aggregate by consecutive_ratio
    print("\nBy consecutive_ratio (averaged across splits and metrics):")
    for cr in consecutive_ratios:
        cr_results = [r for r in results if r['consecutive_ratio'] == cr]
        if cr_results:
            avg_model = sum(r['model_mean'] for r in cr_results) / len(cr_results)
            print(f"  consecutive_ratio={cr}: avg model_mean = {avg_model:.6f} (n={len(cr_results)})")
    
    # Aggregate by predictor_loss_weight
    print("\nBy predictor_loss_weight (averaged across splits and metrics):")
    for plw in predictor_loss_weights:
        plw_results = [r for r in results if r['predictor_loss_weight'] == plw]
        if plw_results:
            avg_model = sum(r['model_mean'] for r in plw_results) / len(plw_results)
            print(f"  predictor_loss_weight={plw}: avg model_mean = {avg_model:.6f} (n={len(plw_results)})")
    
    # Count missing combinations
    total_expected = len(splits) * len(metrics) * len(consecutive_ratios) * len(predictor_loss_weights)
    missing = total_expected - len(results)
    if missing > 0:
        print(f"\nWarning: {missing} combinations are missing out of {total_expected} expected")


if __name__ == '__main__':
    main()
