experiment_name: snapMMD_MFM_${dataset_name}

match_criteria:
  dataset:
    dataset_name: ${dataset_name}
  sampling:
    weight_mode: ${experiment.weight_mode}
    selective_pairing_mode: ${experiment.selective_pairing_mode}
    num_samples: ${experiment.num_samples}
    exponential_weight_scale: ${experiment.exponential_weight_scale}
  experiment:
    generator_source_only: ${experiment.generator_source_only}

# Optional, controls how we name the figures subfolder beyond experiment_name
naming_parameters:
  - dataset.dataset_name
  - sampling.weight_mode
  - sampling.selective_pairing_mode
  - experiment.generator_source_only

output_folder: figures
default_seed_for_plots: 1

