# @package _global_.generator
_target_: generator.energy.EnergyGenerator
model: ${model}  # This will be instantiated first
noise_dim: ${experiment.latent_dim} 
sigma_min: 1.0
m: 16
lambda_energy: 1.0