# @package _global_.generator
_target_: generator.esm2_dfm_uniform_seq2seq.ESM2_DFM_Generator
model_name: ${experiment.esm_model_name}
latent_dim: ${experiment.latent_dim}
condition_dim: ${experiment.condition_dim}
freeze_esm2: ${experiment.freeze_esm2}
condition_method: ${experiment.condition_method}
temperature: ${experiment.temperature}
max_length: ${experiment.max_length}
use_gradient_checkpointing: ${experiment.use_gradient_checkpointing}
precision: ${experiment.precision}