# @package _global_.generator
_target_: generator.progen.Progen2Generator
progen2_name: 'hugohrban/progen2-small'
latent_dim: ${experiment.latent_dim}
condition_dim: 256
freeze_progen2: false
condition_method: "prefix"
temperature: 1.0
max_length: ${experiment.max_length_progen}