# @package _global_
# Sinkhorn generator with UNet for images
defaults:
  - override /model: unet

generator:
  _target_: generator.direct.DirectGenerator
  model: ${model}
  loss_type: sinkhorn
  noise_dim: ${experiment.latent_dim}
  flatten_for_model: false
  loss_params:
    reg: 0.1
    p: 2
    max_iter: 20

