# @package _global_
defaults:
  - override /model: direct_mlp_trellis_mfm

generator:
  _target_: generator.direct.DirectGenerator
  model: ${model}
  loss_type: swd
  noise_dim: ${experiment.latent_dim}
  loss_params:
    n_projections: 100
    p: 2
