# @package _global_.sampling
_target_: sampler.default.Sampler
weight_mode: ${experiment.weight_mode}
num_samples: ${experiment.num_samples}
replacement: true
const_weight: 1.0 
selective_pairing_mode: ${experiment.selective_pairing_mode}
exponential_weight_scale: ${experiment.exponential_weight_scale}