# @package _global_.sampling

# Unidirectional sampling - only samples with dt > 0 get positive weight
mode: "unidirectional"
num_samples: ${experiment.num_samples}
replacement: true
const_weight: 1.0  # Weight for samples with dt > 0 
time_index_path: ${experiment.time_index_path}
time_scale: ${experiment.time_scale}