# @package _global_.dataset
_target_: datasets.snapMMD_PBMC.SnapMMDPBMC
data_dir: data/realdata
data_name: processed_pbmc_data_sub500_every_2_until20.npz
# TODO: make sure data_shape is correct.
data_shape: [30]
seed: ${seed} 
testing_method: forecast