# @package _global_.dataset
_target_: datasets.supervised_datasets.SupervisedMVNDataset
n_sets: 50000
set_size: ${experiment.set_size}
data_shape: [2]
seed: ${seed}
# Restricted mean support (smaller square) compared to mvn [0, 5]
prior_mu: [0, 2.5]
prior_cov_df: 10
prior_cov_scale: 1
# Linear transformation parameters
transform_scale: 1.0
bias_scale: 1.0
