# @package _global_.dataset
_target_: datasets.tcr.TCRDataset

seed: ${seed}
set_size: ${experiment.set_size}

data_dir: data/tcr
data_file: tcr_tokenized_data.pt
esm_name: facebook/esm2_t6_8M_UR50D
progen_name: hugohrban/progen2-small
max_length: 30
tokenize: false
within_patient: ${experiment.within_patient}
split: ${experiment.split}
test_fraction: ${experiment.test_fraction}