# @package _global_.dataset
_target_: datasets.mfm_trellis.trellis_dataset

split_name: ${experiment.split_name}
set_size: ${experiment.set_size}
split_mode: "train"

ot_coupling: ${experiment.ot_coupling}
# TODO: needs to be changed to 45 if we include the one-hot cell type during encoding.
data_shape: [43]