# @package _global_.predictor
_target_: predictor.dt_conditioned_predictor.DTConditionedMLPPredictor
latent_dim: ${experiment.latent_dim}
hidden_dim: 128
num_layers: 2
conditioning_mode: "sinusoidal"
dt_embed_dim: 16
normalize_dt: true 