# @package _global_.predictor
_target_: predictor.predictor.Predictor
latent_dim: ${experiment.latent_dim}
model_type: "mlp"
model_args:
  hidden_dim: 128
  num_layers: 2
conditioning_mode: "concat"
condition_type: ${experiment.predictor_condition_type}
d_embed_dim: 16
loss_type: cosine

