# @package _global_.predictor
_target_: predictor.predictor.Predictor
latent_dim: ${experiment.latent_dim}
model_type: "ridge"
model_args:
  ridge_alpha: 1e-3
conditioning_mode: "concat"
condition_type: ${experiment.predictor_condition_type}
d_embed_dim: 16
loss_type: cosine

